#!/usr/bin/env bash
#
# healthcheck.sh — is the Caelestia-on-Omarchy layering actually healthy?
#
# Read-only. Prints expect vs actual for every fact the layering depends on,
# and exits non-zero if any of them disagree. Run it after installing, after
# `omarchy update`, and any time something feels off.
#
# Where a line disagrees, THE SYSTEM WINS. Fix the system, or find out why the
# expectation is wrong — do not edit this file to make the red go away.
#
# Nothing here is hardcoded to one machine: the theme is read back from Omarchy
# rather than asserted, so this is the same check on every install.

set -uo pipefail

pass=0; fail=0
ck() { # ck <label> <expect> <actual> — a prefix match, so long values can be cut
  local mark
  if [[ $3 == "$2"* ]]; then mark=$'\033[32m✓\033[0m'; pass=$((pass+1))
  else                       mark=$'\033[31m✗\033[0m'; fail=$((fail+1)); fi
  printf '%s %-26s expect %-30s actual %s\n' "$mark" "$1" "$2" "${3:-<empty>}"
}

CAE="$HOME/.local/share/caelestia-shell"
BRIDGE="$HOME/.config/omarchy/bridges/caelestia"
CAE_CFG="$HOME/.config/caelestia/shell.json"
OM_CFG="$HOME/.config/omarchy/shell.json"

echo "── the two shells ──────────────────────────────────────────────────────"
ck "quickshell processes"   "2"                        "$(pgrep -cx quickshell)"
ck "omarchy shell"          "running"                  "$(pgrep -f 'p /usr/share/omarchy/shell' >/dev/null && echo running || echo MISSING)"
ck "omarchy-shell ping"     "ok"                       "$(omarchy-shell shell ping 2>&1)"
ck "caelestia unit"         "active"                   "$(systemctl --user is-active caelestia-shell.service 2>&1)"
ck "guard unit"             "active"                   "$(systemctl --user is-active caelestia-notif-guard.service 2>&1)"
ck "units enabled"          "enabled enabled"          "$(systemctl --user is-enabled caelestia-shell.service caelestia-notif-guard.service 2>&1 | tr '\n' ' ')"

echo
echo "── the notification bus (this is the one that matters) ─────────────────"
# If Caelestia owns this, toasts still appear and nothing looks wrong -- but the
# crash toast's click is silently dead, because its command rides in a private
# hint only Omarchy's shell reads. See README, "The notification race".
ck "bus owner"              "/usr/share/omarchy/shell" "$(busctl --user status org.freedesktop.Notifications 2>/dev/null | sed -n 's/.*-p //p')"

echo
echo "── who draws what ──────────────────────────────────────────────────────"
ck "bar.id"                 "thepiratefox.nullbar"     "$(jq -r '.bar.id // "<unset>"' "$OM_CFG" 2>/dev/null)"
ck "omarchy bar surfaces"   "0"                        "$(hyprctl layers 2>/dev/null | grep -c 'namespace: omarchy-bar')"
ck "caelestia drawers"      "1"                        "$(hyprctl layers 2>/dev/null | grep -c 'namespace: caelestia-drawers')"
ck "omarchy background"     "1"                        "$(hyprctl layers 2>/dev/null | grep -c 'namespace: omarchy-background')"
ck "wallpaper"              "present"                  "$([ -e "$HOME/.local/state/omarchy/current/background" ] && echo present || echo MISSING)"
ck "omarchy.osd disabled"   "yes"                      "$(jq -r 'if ((.disabledPlugins//[])|index("omarchy.osd")) then "yes" else "NO - both OSDs will fire" end' "$OM_CFG" 2>/dev/null)"

echo
echo "── theming (Caelestia follows Omarchy, one direction) ──────────────────"
# Expectation is READ BACK from Omarchy, not asserted, so this works on any theme.
ck "scheme flavour"         "$(cat "$HOME/.local/state/omarchy/current/theme.name" 2>/dev/null)" \
                            "$(jq -r '.flavour' "$HOME/.local/state/caelestia/scheme.json" 2>/dev/null || echo MISSING)"
ck "scheme mode"            "$(omarchy-theme-color mode 2>/dev/null)" \
                            "$(jq -r '.mode' "$HOME/.local/state/caelestia/scheme.json" 2>/dev/null || echo MISSING)"
ck "bridge self-check"      "PASS"                     "$("$BRIDGE/omarchy-to-caelestia-scheme" --check 2>&1 | head -c 58)"
ck "theme hook"             "present"                  "$([ -e "$HOME/.config/omarchy/hooks/theme-set.d/50-caelestia-scheme" ] && echo present || echo MISSING)"

echo
echo "── idle and lock ───────────────────────────────────────────────────────"
# 310 is not a typo. Both monitors arm from the same last-input moment, so a
# lock timeout <= the screensaver's fires alongside it. See README, "Idle and lock".
ck "omarchy screensaver"    "300"                      "$(jq -r '.idle.screensaver' "$OM_CFG" 2>/dev/null)"
ck "omarchy timed lock"     "86400"                    "$(jq -r '.idle.lock' "$OM_CFG" 2>/dev/null)"
ck "omarchy idle service"   "true"                     "$(omarchy-shell idle status 2>/dev/null | jq -r '.enabled')"
ck "caelestia idle timeout" "310 -> caelestia-lock"    "$(jq -r '.general.idle.timeouts[0] | "\(.timeout) -> \(.idleAction[0]|split("/")|last)"' "$CAE_CFG" 2>/dev/null)"
ck "caelestia lock.enabled" "true"                     "$(jq -r '.lock.enabled' "$CAE_CFG" 2>/dev/null)"
ck "lockBeforeSleep"        "false"                    "$(jq -r '.general.idle.lockBeforeSleep' "$CAE_CFG" 2>/dev/null)"
ck "stay-awake"             "absent"                   "$([ -e "$HOME/.local/state/omarchy/indicators/stay-awake" ] && echo PRESENT || echo absent)"
ck "caelestia-lock"         "present"                  "$([ -x "$BRIDGE/caelestia-lock" ] && echo present || echo MISSING)"
ck "session menu"           "true"                     "$(jq -r '.session.enabled' "$CAE_CFG" 2>/dev/null)"

echo
echo "── hygiene ─────────────────────────────────────────────────────────────"
ck "caelestia-start"        "present"                  "$([ -x "$BRIDGE/caelestia-start" ] && echo present || echo MISSING)"
ck "notif guard script"     "present"                  "$([ -x "$BRIDGE/caelestia-notif-guard" ] && echo present || echo MISSING)"
# More than one means Caelestia was started outside its unit at some point: the
# nmcli child only gets reaped by the unit's cgroup.
ck "nmcli monitor children" "1"                        "$(pgrep -cf 'nmcli monitor')"
# caelestia-cli would have written all of these. It must not be installed.
ck "caelestia-cli damage"   "0 present"                "$(ls -d "$HOME/.config/gtk-3.0/gtk.css" "$HOME/.config/gtk-4.0" "$HOME/.config/qt5ct" "$HOME/.config/qt6ct" "$HOME/.config/hypr/scheme" 2>/dev/null | wc -l) present"
ck "quickshell package"     "quickshell"               "$(pacman -Qq quickshell 2>/dev/null || echo 'MISSING - quickshell-git?')"
ck "hypr config errors"     "(none)"                   "$(hyprctl configerrors 2>/dev/null | head -1 | grep -q . && hyprctl configerrors | head -1 || echo '(none)')"
ck "launcher keybind"       "App launcher"             "$(omarchy menu keybindings --print 2>/dev/null | sed -n 's/^ALT + SPACE *→ *//p')"

echo
if ((fail)); then
  printf '\033[31m%d of %d checks failed.\033[0m See README "If it goes wrong".\n' "$fail" "$((pass+fail))"
  exit 1
fi
printf '\033[32mAll %d checks passed.\033[0m\n' "$pass"
